# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# github actions 中文文档 https://docs.github.com/cn/actions/getting-started-with-github-actions

name: deploy for dev

on:
    push:
        branches:
            - 'dev' # 只针对 dev 分支
        paths:
            # - '__test__/**' # dev 不需要立即测试
            - '.github/workflows/*'
            - 'bin/*'
            - 'mysql/**'
            - 'script/**'
            - 'shell/**'
            - 'src/**'
            - '.env'
            - 'Dockerfile'
            - 'docker-compose.yml'

jobs:
    deploy-dev:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: set ssh key # 临时设置 ssh key
              run: |
                  mkdir -p ~/.ssh/
                  echo "${{secrets.WFP_ID_RSA}}" > ~/.ssh/id_rsa # secret 在这里配置https://github.com/unclepan/server-monitor/settings/secrets/actions
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan "43.129.75.108" >> ~/.ssh/known_hosts
            - name: deploy # 部署
              run: |
                  ssh work@43.129.75.108 "
                    # 【注意】用 work 账号登录，手动创建 /home/work/app 目录
                    # 然后 git clone https://unclepan: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@github.com/unclepan/server-monitor.git -b dev （私有仓库，使用 github 用户名和密码）
                    # 记得删除 origin ，否则会暴露 github 密码

                    cd /home/work/app/server-monitor;
                    git remote add origin https://unclepan:${{secrets.WFP_PASSWORD}}@github.com/unclepan/server-monitor.git
                    git checkout dev;
                    git pull origin dev; # 重新下载最新代码
                    git remote remove origin; # 删除 origin ，否则会暴露 github 密码
                    启动 docker
                    docker compose build server-monitor; # 和 docker-compose.yml service 名字一致
                    docker compose up -d;
                  "
            - name: delete ssh key # 删除 ssh key
              run: rm -rf ~/.ssh/id_rsa
