name: test

on:
    push:
        branches:
            - main
        paths:
            - '__test__/**'
            - '.github/workflows/*'
            - 'bin/*'
            - 'mysql/**'
            - 'script/**'
            - 'shell/**'
            - 'src/**'
            - '.env'

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 16
            - name: lint and test
              run: |
                  npm i
                  npm run lint
                  npm run test:remote
